import { SlashCommandBuilder } from 'discord.js';
const s=(name:string,description:string)=>new SlashCommandBuilder().setName(name).setDescription(description);
export const commands=[
  s('ask','Talk to BibiAI.').addStringOption(o=>o.setName('prompt').setDescription('Question or request').setRequired(true).setMaxLength(1500)).addAttachmentOption(o=>o.setName('image').setDescription('Image or short video')).addAttachmentOption(o=>o.setName('video').setDescription('Short video')),
  s('join','Server address and modpack installation instructions.'),
  s('mc','Minecraft operations.').addSubcommand(o=>o.setName('status').setDescription('Check server status.')).addSubcommand(o=>o.setName('diagnostics').setDescription('Operator diagnostics.')).addSubcommand(o=>o.setName('start').setDescription('Start the server.')).addSubcommand(o=>o.setName('recover').setDescription('Request recovery.')).addSubcommand(o=>o.setName('fix').setDescription('Make a repair plan.').addStringOption(v=>v.setName('issue').setDescription('What is broken?').setRequired(true).setMaxLength(1500))),
  s('rcon','Run an allowlisted server command.').addStringOption(o=>o.setName('command').setDescription('One command').setRequired(true).setMaxLength(200)),
  s('memory','Manage durable notes.').addSubcommand(o=>o.setName('list').setDescription('List stored notes.')).addSubcommand(o=>o.setName('add').setDescription('Save a note.').addStringOption(v=>v.setName('text').setDescription('Fact to remember').setRequired(true).setMaxLength(500))).addSubcommand(o=>o.setName('remove').setDescription('Delete one note.').addStringOption(v=>v.setName('id').setDescription('Note ID').setRequired(true))).addSubcommand(o=>o.setName('clear').setDescription('Delete all durable notes.')),
  s('snitch','Report misconduct with evidence.').addUserOption(o=>o.setName('user').setDescription('Reported member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('What happened?').setRequired(true).setMaxLength(700)).addStringOption(o=>o.setName('evidence').setDescription('Evidence description or link').setMaxLength(300)).addAttachmentOption(o=>o.setName('evidence_file').setDescription('Image/video evidence')).addAttachmentOption(o=>o.setName('evidence_file_2').setDescription('Second evidence file')).addAttachmentOption(o=>o.setName('evidence_file_3').setDescription('Third evidence file')),
  s('moderation','Moderation diagnostics.').addSubcommand(o=>o.setName('check').setDescription('Check permissions and role hierarchy.').addUserOption(v=>v.setName('user').setDescription('Member').setRequired(true))),
  s('vacation','Vacation stewardship.').addSubcommand(o=>o.setName('status').setDescription('Show vacation status.')).addSubcommand(o=>o.setName('checkin').setDescription('Operator status report.')),
  s('tts','Speak in your voice channel.').addSubcommand(o=>o.setName('say').setDescription('Speak supplied text.').addStringOption(v=>v.setName('text').setDescription('Text to speak').setRequired(true).setMaxLength(300))).addSubcommand(o=>o.setName('leave').setDescription('Stop and leave voice.')),
  s('listen','Listen to your speech for up to 15 seconds and reply.'),
  s('roles','Self-select roles and moderator role management.').addSubcommand(o=>o.setName('menu').setDescription('Show the self-select role menu.')).addSubcommand(o=>o.setName('add').setDescription('Assign an allowed role.').addUserOption(v=>v.setName('user').setDescription('Member').setRequired(true)).addRoleOption(v=>v.setName('role').setDescription('Role').setRequired(true))).addSubcommand(o=>o.setName('remove').setDescription('Remove a role.').addUserOption(v=>v.setName('user').setDescription('Member').setRequired(true)).addRoleOption(v=>v.setName('role').setDescription('Role').setRequired(true))),
  s('privacy','Control BibiAI data processing.').addSubcommand(o=>o.setName('optout').setDescription('Stop processing and delete your BibiAI records.')).addSubcommand(o=>o.setName('optin').setDescription('Explicitly resume processing with an empty history.')).addSubcommand(o=>o.setName('restore').setDescription('Admin: remove a member from privacy mode.').addUserOption(v=>v.setName('user').setDescription('Member to restore').setRequired(true))).addSubcommand(o=>o.setName('status').setDescription('Show your privacy preference.')),
  s('appeal','Appeal a moderation decision.').addSubcommand(o=>o.setName('submit').setDescription('Submit an appeal.').addStringOption(v=>v.setName('reason').setDescription('Why should the decision change?').setRequired(true).setMaxLength(1500)).addStringOption(v=>v.setName('email').setDescription('Optional email for correspondence').setMaxLength(254))).addSubcommand(o=>o.setName('status').setDescription('View your appeal.')).addSubcommand(o=>o.setName('verify').setDescription('Verify your email address.').addStringOption(v=>v.setName('case').setDescription('Appeal ID').setRequired(true)).addStringOption(v=>v.setName('code').setDescription('Code from the email').setRequired(true))),
].map(c=>c.toJSON());
